<div class="slider">
    <div class="rev_slider_wrapper">
        <div id="slider1" class="rev_slider"  data-version="5.0">
            <ul>
                <li data-transition="zoomout" data-slotamount="10" data-masterspeed="3000" >
                    <img src="<?php echo get_template_directory_uri() ?>/img/res/nebo-nemn-golub2.jpg"  alt="Наша цель - ВАШЕ ВЫЗДОРОВЛЕНИЕ!|centr-voskresenie.ru" title="МЫ ВАМ ПОМОЖЕМ" class="rev-slidebg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-no-retina />
                    <div class="tp-caption slide-title1 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['60','60','60','60']" data-voffset="['0','0','0','0']" data-fontsize="['49','49','29','19']" data-lineheight="['49','49','29','19']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:90;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="; white-space: nowrap;">МЫ ВАМ <span>ПОМОЖЕМ</span></div>

                    <div class="tp-caption slide-subtitle1 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['140','140','140','140']" data-voffset="['0','0','0','0']" data-fontsize="['20','25','15','15']" data-lineheight="['25','25','15','15']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:45;rZ:30;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:right(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">Целью нашего центра является </div>
                    <div class="tp-caption slide-subtitle1 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['170','150','150','150']" data-voffset="['0','0','0','0']" data-fontsize="['20','25','15','15']" data-lineheight="['25','25','15','15']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:45;rZ:30;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:right(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">выздоровление людей, страдающих  </div>
                    <div class="tp-caption slide-subtitle1 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['200','180','180','180']" data-voffset="['0','0','0','0']" data-fontsize="['20','25','15','15']" data-lineheight="['25','25','15','15']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:45;rZ:30;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:right(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">алкогольной и наркотической зависимостью.</div>

                    <?php
                    $idObj = get_category_by_slug('o-tsentre');/*Получаем категорию по слагу*/
                    $id = $idObj->term_id;
                    ?>

                    <a href="<?php echo get_category_link($id) ?>" title="<?php echo get_cat_name($id) ?>" class="tp-caption slide-button colored-box tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['240','220','220','220']" data-voffset="['0','0','0','0']" data-fontsize="['13','13','13','13']" data-lineheight="['15','15','13','13']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="y:bottom(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">УЗНАТЬ БОЛЬШЕ</a>

                    <!--<div class="tp-caption tp-resizeme rs-parallaxlevel-2" data-x="['right','right','right','right']" data-hoffset="['0','0','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']" data-transform_idle="o:1;" data-transform_in="y:bottom(R);z:0;rX:90;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Elastic.easeInOut;" data-transform_out="x:right(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2300" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-no-retina><img src="img/res/zdorovie-ludi.png" alt="" data-ww="['635px','635px','200px','170px']" data-hh="['445px','445px','251px','213px']" itemprop="image" data-no-retina /></div>-->
                    <div class="tp-caption tp-resizeme rs-parallaxlevel-2" data-x="['500','right','right','right']" data-hoffset="['0','0','0','0']" data-y="['bottom','bottom','bottom','bottom']" data-voffset="['0','0','0','0']" data-transform_idle="o:1;" data-transform_in="y:bottom(R);z:0;rX:90;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Elastic.easeInOut;" data-transform_out="x:right(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2300" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-no-retina><img src="<?php echo get_template_directory_uri() ?>/img/res/zdorovie-ludi2.png" alt="" data-ww="['749px','749px','10px','10px']" data-hh="['410px','410px','10px','10px']" itemprop="image" data-no-retina /></div>
                </li>

                <li data-transition="zoomin" data-slotamount="10" data-masterspeed="3000" >
                    <img src="<?php echo get_template_directory_uri() ?>/img/res/komfort-i-uyut.jpg"  alt="Реабилитация в Центре|centr-voskresenie.ru" title="Рабилитация в центре Воскресение" class="rev-slidebg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-no-retina />
                    <div class="tp-caption slide-title2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['100','100','100','100']" data-voffset="['0','0','0','0']" data-fontsize="['37','37','27','27']" data-lineheight="['37','37','27','27']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:1.5;sY:0.9;skX:0.9;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="; white-space: nowrap;">РЕАБИЛИТАЦИЯ <span>В ЦЕНТРЕ</span></div>

                    <div class="tp-caption colored-box slide-subtitle2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['170','170','170','170']" data-voffset="['0','0','0','0']" data-fontsize="['19','19','15','15']" data-lineheight="['25','25','20','20']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap; color: #ffffff;">6-ти месячная программа реабилитации</div>
                    <div class="tp-caption colored-box slide-subtitle2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['210','170','170','170']" data-voffset="['0','0','0','0']" data-fontsize="['19','19','15','15']" data-lineheight="['25','25','20','20']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap; color: #ffffff;">в комфорте и уюте нашего Центра</div>

                    <div class="tp-caption white-bg slide-subtitle2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['250','220','220','220']" data-voffset="['0','0','0','0']" data-fontsize="['18','18','15','15']" data-lineheight="['25','25','20','20']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">Мы создали уникальную программу выздоровления</div>

                    <?php
                    $idObj = get_category_by_slug('ekskursiya-po-tsentru');/*Получаем категорию по слагу*/
                    $id = $idObj->term_id;
                    ?>

                    <a href="<?php echo get_category_link($id) . '#usloviya-progiv' ?>" title="Условия проживания" class="tp-caption dark-bg slide-button slide-button2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['330','300','300','300']" data-voffset="['0','0','0','0']" data-fontsize="['14','14','13','13']" data-lineheight="['15','15','13','13']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:-45;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">УЗНАТЬ БОЛЬШЕ</a>
                </li>

                <li data-transition="fade" data-slotamount="10" data-masterspeed="3000" >
                    <img src="<?php echo get_template_directory_uri() ?>/img/res/domashnya-kuhnya.jpg"  alt="Качественное питание в центре Воскресенье|centr-voskresenie.ru" title="Домашняя кухня в Центре Воскресенье" class="rev-slidebg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-no-retina />
                    <div class="tp-caption slide-title3 tp-resizeme rs-parallaxlevel-2" data-x="['500','500','500','500']" data-hoffset="['0','0','0','0']" data-y="['100','100','100','100']" data-voffset="['0','0','0','0']" data-fontsize="['36','36','26','26']" data-lineheight="['36','36','26','26']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="x:[105%];z:0;rX:45deg;rY:0deg;rZ:90deg;sX:1;sY:1;skX:0;skY:0;s:2000;e:Power4.easeInOut;" data-transform_out="y:[100%];s:1000;e:Power2.easeInOut;s:1000;e:Power2.easeInOut;" data-mask_in="x:0px;y:0px;" data-mask_out="x:inherit;y:inherit;" data-start="1700" data-splitin="chars" data-splitout="none" data-responsive_offset="on" data-elementdelay="0.05" style="; white-space: nowrap;">Домашняя кухня</div>

                    <div class="tp-caption light-bg slide-subtitle3 tp-resizeme rs-parallaxlevel-2" data-x="['500','500','500','500']" data-hoffset="['0','0','0','0']" data-y="['170','170','170','170']" data-voffset="['0','0','0','0']" data-fontsize="['26','26','20','20']" data-lineheight="['26','26','20','20']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:right(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">Вкусное питание в Центре</div>

                    <div class="tp-caption light-bg slide-subtitle3 tp-resizeme rs-parallaxlevel-2" data-x="['500','500','500','500']" data-hoffset="['0','0','0','0']" data-y="['213','213','213','213']" data-voffset="['0','0','0','0']" data-fontsize="['26','26','20','20']" data-lineheight="['26','26','20','20']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:right(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space:">Даёт силы для выздоровления</div>

                    <?php
                    $idObj = get_category_by_slug('ekskursiya-po-tsentru');/*Получаем категорию по слагу*/
                    $id = $idObj->term_id;
                    ?>

                    <a href="<?php echo get_category_link($id) . '#usloviya-pitaniya' ?>" title="Условия питания" class="tp-caption dark-bg slide-button slide-button2 tp-resizeme rs-parallaxlevel-2" data-x="['500','500','500','500']" data-hoffset="['0','0','0','0']" data-y="['300','300','300','300']" data-voffset="['0','0','0','0']" data-fontsize="['14','14','13','13']" data-lineheight="['15','15','13','13']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:-45;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:right(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">УЗНАТЬ БОЛЬШЕ</a>
                </li>

                <li data-transition="zoomin" data-slotamount="10" data-masterspeed="3000" >
                    <img src="<?php echo get_template_directory_uri() ?>/img/res/ruka-pomoshi2.jpg"  alt="Наш центр – это школа любви и дружбы|centr-voskresenie.ru" title="Наш центр – это школа любви и дружбы" class="rev-slidebg" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-no-retina />
                    <div class="tp-caption slide-title2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['100','100','100','100']" data-voffset="['0','0','0','0']" data-fontsize="['37','37','27','27']" data-lineheight="['37','37','27','27']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:1.5;sY:0.9;skX:0.9;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1700" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="; white-space: nowrap;">ШКОЛА <span>ЛЮБВИ И ДРУЖБЫ</span></div>

                    <div class="tp-caption colored-box slide-subtitle2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['170','170','170','170']" data-voffset="['0','0','0','0']" data-fontsize="['18','18','15','15']" data-lineheight="['25','25','20','20']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="1900" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap; color: #ffffff;">Мы вместе восстановливаем разрушенные семейные отношения, </div>

                    <div class="tp-caption white-bg slide-subtitle2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['220','220','220','220']" data-voffset="['0','0','0','0']" data-fontsize="['18','18','15','15']" data-lineheight="['25','25','20','20']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:0;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2100" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">обретаем радость трезвой жизни. Начинаем жить долго и счастливо!</div>

                    <?php
                    $idObj = get_category_by_slug('kak-myi-rabotaem');/*Получаем категорию по слагу*/
                    $id = $idObj->term_id;
                    ?>

                    <a href="<?php echo get_category_link($id) ?>" title="<?php echo get_cat_name($id) ?>" class="tp-caption dark-bg slide-button slide-button2 tp-resizeme rs-parallaxlevel-2" data-x="['left','left','left','left']" data-hoffset="['0','0','0','0']" data-y="['300','300','300','300']" data-voffset="['0','0','0','0']" data-fontsize="['14','14','13','13']" data-lineheight="['15','15','13','13']" data-width="['none','none','none','400']" data-height="none" data-whitespace="['nowrap','nowrap','nowrap','normal']" data-transform_idle="o:1;" data-transform_in="z:0;rX:-45;rY:0;rZ:0;sX:0.9;sY:0.9;skX:0;skY:0;opacity:0;s:2000;e:Back.easeInOut;" data-transform_out="x:left(R);s:2000;e:Back.easeIn;s:1000;e:Back.easeIn;" data-start="2300" data-splitin="none" data-splitout="none" data-responsive_offset="on" style="white-space: nowrap;">УЗНАТЬ БОЛЬШЕ</a>
                </li>

            </ul>

        </div>

    </div><!-- REVOLUTION SLIDER -->
</div>